"""Added interests system

Revision ID: 671bd617f9de
Revises: 88b89c9814af
Create Date: 2026-05-07 22:58:22.894584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '671bd617f9de'
down_revision = '88b89c9814af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('profile_interests',
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('interest_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_interests')
    op.drop_table('interests')
    # ### end Alembic commands ###
