"""empty message

Revision ID: 88b89c9814af
Revises: 4106ab3d958f
Create Date: 2025-04-27 12:00:03.702048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88b89c9814af'
down_revision = '4106ab3d958f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_fk', sa.Integer(), nullable=False),
    sa.Column('fav_user_id_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fav_user_id_fk'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id_fk'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favorites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id_fk', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fav_user_id_fk', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['fav_user_id_fk'], ['users.id'], name='favorites_fav_user_id_fk_fkey'),
    sa.ForeignKeyConstraint(['user_id_fk'], ['users.id'], name='favorites_user_id_fk_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorites_pkey')
    )
    op.drop_table('favourites')
    # ### end Alembic commands ###
